 pipeline {

    agent any

    stages {

        stage('Build') {
            steps {
                sh '''
                    ls
                    make clean all
                '''
            }

            post {
                success {
                   echo success
                }
            }
        }

        stage('Test') {
            steps {
                sh './a.out'
            }

            post {
                always {
                    echo test
                }
            }
        }

    }
}
